version: '3'
services:
  server:
    build: 
      context: ./server
    container_name: server
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3001:3000"
    depends_on:
      - server